name: BDS-TEST
favicon: null
layout_spectrum: 0.73722
typography_spectrum: 0.3329
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdfdfd'
    - '#d3c9b7'
    - '#a59684'
    - '#7a683c'
  brandStrength: 0.75
  lightness: 0.9875446127261966
  saturation: 0.4135935481172055
  rhythmicContrast: 0.7958771751727909
purpose: []
